In [1]:
from sklearn.preprocessing import MinMaxScaler

import pandas as pd
import numpy as np


In [24]:
data = [
    [-1,2],
    [-0.5,6],
    [0,10],
    [1,18]
]
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [28]:
# 归一化
scaler = MinMaxScaler()
scaler = scaler.fit(data)
result = scaler.transform(data)
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [29]:
# 归一化
scaler = MinMaxScaler()
result = scaler.fit_transform(data)
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [32]:
# 逆转 归一化结果
result_ = scaler.inverse_transform(result)
result_

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [33]:
# 归一化到指定区间
scaler = MinMaxScaler(feature_range=[5,10])
result = scaler.fit_transform(data)
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [37]:
# 当数据集非常大的时候 fit会报错 使用partial_fit
import numpy as np
X = np.array([
    [-1,    2],
    [-0.5,  6],
    [0,     10],
    [1,     18]
])
X.min(axis=0)

array([-1.,  2.])

In [35]:
X.min(axis=1)

array([-1. , -0.5,  1. ])

In [39]:
X_nor = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_nor

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])